version: '2.1'
services:
  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_USER: app
      MARIADB_PASSWORD: app
      MARIADB_DATABASE: xilab
    ports:
      - "3306:3306"
    volumes:
      # Unix/MacOs: /xilab/mysql:/var/xilab/mysql
      # Windows:    c:\xilab\mysql:/var/xilab/mysql
      #- Set path according to your OS
      - D:\data\xilab:/var/xilab/mysql
    networks:
      - spring-cloud-network
    healthcheck:
      test: "exit 0"
  xilab:
    container_name: xilab
    depends_on:
      database:
        condition: service_healthy
    build: .
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge