version: '2.1'
services:
  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_USER: app
      MARIADB_PASSWORD: app
      MARIADB_DATABASE: xilab
    ports:
      - "3306:3306"
    volumes:
      # example windows: - d:\data\xilab\mysql:/var/lib/mysql
      # example unix/max: /mnt/d/xilab/mysql:/var/lib/mysql
      - d:\data\xilab\mysql:/var/lib/mysql
    networks:
      - spring-cloud-network
    healthcheck:
      test: "exit 0"
  xilab:
    container_name: xilab
    depends_on:
      database:
        condition: service_healthy
    build:
      context: xilab
      dockerfile: Dockerfile
    image: xilab:0.0.1
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge